server:
  port: 9030
spring:
  application:
    name: Bank-Config-Service
  #Apuntar el path de la ruta
  cloud:
    config:
      server:
        git:
          uri: https://github.com/byNo0dle/config-service-data.git
          search-paths: '{application}'
