server:
  port: 9007
spring:
  application:
    name: Bank-Config-Service
  #Apuntar el path a la ruta
cloud:
  config:
    server:
      git:
        uri: https://github.com/byNo0dle
        default-label: NFSC
        search-paths: /config-service-data
